# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvDashboard UI Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Investment Dashboard")
        MainWindow.resize(250, 175)
        MainWindow.setMinimumSize(QtCore.QSize(250, 175))
        MainWindow.setMaximumSize(QtCore.QSize(250, 175))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 10, 61, 22))
        self.lineEdit.setObjectName("lineEdit")
        
        self.price_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.price_checkBox.setGeometry(QtCore.QRect(20, 60, 140, 16))
        self.price_checkBox.setObjectName("price_checkBox")
        self.div_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.div_checkBox.setGeometry(QtCore.QRect(20, 40, 140, 16))
        self.div_checkBox.setObjectName("div_checkBox")
        
        self.clear_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clear_pushButton.setGeometry(QtCore.QRect(20, 100, 100, 26))
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.download_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.download_pushButton.setGeometry(QtCore.QRect(120, 100, 100, 26))
        self.download_pushButton.setObjectName("download_pushButton")
        
        self.clear_pushButton.clicked.connect(self.clear)
        self.download_pushButton.clicked.connect(self.download)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setAccessibleDescription(_translate("MainWindow", "i.e. AAPL"))
        self.div_checkBox.setText(_translate("MainWindow", "Dividend History"))
        self.label.setText(_translate("MainWindow", "Enter Ticker Symbol:"))
        self.price_checkBox.setText(_translate("MainWindow", "Stock Price History"))
        self.clear_pushButton.setText(_translate("MainWindow", "Clear"))
        self.download_pushButton.setText(_translate("MainWindow", "Download"))

    def download(self):
        if self.price_checkBox.isChecked():
            print("Download price history data")
        if self.div_checkBox.isChecked():
            print("Download dividend history data")
    
    def clear(self):
        self.lineEdit.clear()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
